name: Check pushed code
on:
  push:
    branches:
      - main
    release:
      types:
        - created
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    name: "Check pushed code"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: "Install gd script toolkit"
        uses: Scony/godot-gdscript-toolkit@master
      - name: "Check lint"
        run: gdlint .
      - name: "Check formatting"
        run: gdformat --check .
